// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by: bun run scripts/gen-models.ts
// Generated at: 2026-03-02T07:07:55.284Z

import type { Model, SchemaDefinition, InstanceKeys } from '@pkg/orm'

import type CrudTableSchema from '@/models/crud-table/schema'
import type DictDataSchema from '@/models/dict-data/schema'
import type DictTypeSchema from '@/models/dict-type/schema'
import type IpBlacklistSchema from '@/models/ip-blacklist/schema'
import type JobSchema from '@/models/job/schema'
import type JobLogSchema from '@/models/job-log/schema'
import type LoginLogSchema from '@/models/login-log/schema'
import type MenuSchema from '@/models/menu/schema'
import type NoticeSchema from '@/models/notice/schema'
import type NoticeReadSchema from '@/models/notice-read/schema'
import type OperLogSchema from '@/models/oper-log/schema'
import type PermissionSchema from '@/models/permission/schema'
import type PermissionScopeSchema from '@/models/permission-scope/schema'
import type RateLimitRuleSchema from '@/models/rate-limit-rule/schema'
import type RoleSchema from '@/models/role/schema'
import type RoleMenuSchema from '@/models/role-menu/schema'
import type RolePermissionSchema from '@/models/role-permission/schema'
import type SeedLogSchema from '@/models/seed-log/schema'
import type SessionSchema from '@/models/session/schema'
import type SysConfigSchema from '@/models/sys-config/schema'
import type SysFileSchema from '@/models/sys-file/schema'
import type UserResourceUsageSchema from '@/models/user-resource-usage/schema'
import type UserVipSchema from '@/models/user-vip/schema'
import type UsersSchema from '@/models/users/schema'
import type VipResourceLimitSchema from '@/models/vip-resource-limit/schema'
import type VipTierSchema from '@/models/vip-tier/schema'

/** 从 Schema 类推导 Model 类型 */
type ModelOf<C extends abstract new (...args: any) => any> = Model<
  SchemaDefinition,
  InstanceKeys<C>
>

/** 模型注册表类型（自动生成） */
export interface ModelRegistry {
  crud_table: ModelOf<typeof CrudTableSchema>
  dict_data: ModelOf<typeof DictDataSchema>
  dict_type: ModelOf<typeof DictTypeSchema>
  ip_blacklist: ModelOf<typeof IpBlacklistSchema>
  job: ModelOf<typeof JobSchema>
  job_log: ModelOf<typeof JobLogSchema>
  login_log: ModelOf<typeof LoginLogSchema>
  menu: ModelOf<typeof MenuSchema>
  notice: ModelOf<typeof NoticeSchema>
  notice_read: ModelOf<typeof NoticeReadSchema>
  oper_log: ModelOf<typeof OperLogSchema>
  permission: ModelOf<typeof PermissionSchema>
  permission_scope: ModelOf<typeof PermissionScopeSchema>
  rate_limit_rule: ModelOf<typeof RateLimitRuleSchema>
  role: ModelOf<typeof RoleSchema>
  role_menu: ModelOf<typeof RoleMenuSchema>
  role_permission: ModelOf<typeof RolePermissionSchema>
  seed_log: ModelOf<typeof SeedLogSchema>
  session: ModelOf<typeof SessionSchema>
  sys_config: ModelOf<typeof SysConfigSchema>
  sys_file: ModelOf<typeof SysFileSchema>
  user_resource_usage: ModelOf<typeof UserResourceUsageSchema>
  user_vip: ModelOf<typeof UserVipSchema>
  users: ModelOf<typeof UsersSchema>
  vip_resource_limit: ModelOf<typeof VipResourceLimitSchema>
  vip_tier: ModelOf<typeof VipTierSchema>
}

/** Session 相关类型 */
export type SessionRow = import('@pkg/orm').Row<ModelRegistry['session']>
export type SessionInsert = import('@pkg/orm').Insert<ModelRegistry['session']>
export type SessionUpdate = import('@pkg/orm').Update<ModelRegistry['session']>
