/**
 * Model 类型生成脚本
 *
 * 扫描 models/＊/schema.ts，自动生成 core/model.generated.ts 类型定义文件
 *
 * 使用方式：
 *   bun run gen:models        # 手动触发
 *   bun run dev / bun run start  # 启动时自动触发
 */

import { Glob } from 'bun'
import { join } from 'path'

const modelsDir = join(import.meta.dir, '../models')
const outputPath = join(import.meta.dir, '../core/model.generated.ts')

const glob = new Glob('*/schema.ts')
const entries: { folder: string; tableName: string; className: string }[] = []

for await (const file of glob.scan({ cwd: modelsDir })) {
  const folder = file.replace(/\\/g, '/').split('/')[0] // e.g. "crud-table"
  const mod = await import(join(modelsDir, file))
  const tableName = mod.tableName as string

  if (!tableName) {
    console.warn(`⚠️ Skipping ${file}: missing tableName export`)
    continue
  }

  // kebab-case → PascalCase + Schema  e.g. "crud-table" → "CrudTableSchema"
  const className =
    folder
      .split('-')
      .map((s) => s[0].toUpperCase() + s.slice(1))
      .join('') + 'Schema'

  entries.push({ folder, tableName, className })
}

// 按 tableName 排序，保证输出稳定
entries.sort((a, b) => a.tableName.localeCompare(b.tableName))

// ===== 生成文件内容 =====
const lines: string[] = [
  '// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY',
  '// Generated by: bun run scripts/gen-models.ts',
  `// Generated at: ${new Date().toISOString()}`,
  '',
  "import type { Model, SchemaDefinition, InstanceKeys } from '@pkg/orm'",
  '',
]

// import type 行
for (const { folder, className } of entries) {
  lines.push(`import type ${className} from '@/models/${folder}/schema'`)
}

lines.push('')
lines.push('/** 从 Schema 类推导 Model 类型 */')
lines.push(
  'type ModelOf<C extends abstract new (...args: any) => any> = Model<SchemaDefinition, InstanceKeys<C>>',
)
lines.push('')
lines.push('/** 模型注册表类型（自动生成） */')
lines.push('export interface ModelRegistry {')
for (const { tableName, className } of entries) {
  lines.push(`  ${tableName}: ModelOf<typeof ${className}>`)
}
lines.push('}')
lines.push('')

// Session 快捷类型
if (entries.some((e) => e.tableName === 'session')) {
  lines.push('/** Session 相关类型 */')
  lines.push("export type SessionRow = import('@pkg/orm').Row<ModelRegistry['session']>")
  lines.push("export type SessionInsert = import('@pkg/orm').Insert<ModelRegistry['session']>")
  lines.push("export type SessionUpdate = import('@pkg/orm').Update<ModelRegistry['session']>")
  lines.push('')
}

await Bun.write(outputPath, lines.join('\n'))
console.log(`✅ Generated model types → core/model.generated.ts (${entries.length} models)`)
