import { Glob } from 'bun'
import { join, resolve } from 'path'

// ─── 工具函数 ───

/** kebab-case → camelCase */
function kebabToCamel(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
}

/** kebab-case → PascalCase */
function kebabToPascal(s: string): string {
  return s
    .split('-')
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join('')
}

/**
 * 文件路径 → API prefix（与原 core/index.ts fileToPrefix 逻辑一致）
 *   admin/auth/index.ts  → api/admin/auth
 *   _/auth/index.ts      → api/auth
 */
function fileToPrefix(file: string): string {
  const parts = file
    .replace(/\\/g, '/')
    .replace(/\.ts$/, '')
    .split('/')
    .filter((seg) => seg !== '_')
  if (parts.at(-1) === 'index') parts.pop()
  return `api/${parts.join('/')}`
}

/** 文件路径 → 合法 JS 变量名 */
function pathToVar(file: string, prefix: string): string {
  return (
    prefix +
    '_' +
    file
      .replace(/\\/g, '/')
      .replace(/\.ts$/, '')
      .replace(/\/index$/, '')
      .split('/')
      .map((seg) => (seg === '_' ? '$' : kebabToCamel(seg)))
      .join('_')
  )
}

/** 从 schema.ts 文件内容中提取 tableName（纯文本解析，不需要 import 模块） */
function extractTableName(content: string): string | null {
  const match = content.match(/export\s+const\s+tableName\s*=\s*['"]([^'"]+)['"]/)
  return match?.[1] ?? null
}

function header(): string[] {
  return [
    '// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY',
    '// Generated by: bun run scripts/gen-registry.ts',
    `// Generated at: ${new Date().toISOString()}`,
    '',
  ]
}

// ─── 核心生成逻辑 ───

/**
 * 生成所有注册表文件
 * @param backendDir - backend 目录的绝对路径（可选，默认自动推导）
 */
export async function generateRegistry(backendDir?: string) {
  const dir = backendDir ?? resolve(import.meta.dir, '..')
  const modelsDir = join(dir, 'models')
  const apiDir = join(dir, 'api')
  const generatedDir = join(dir, '_generated')

  // 确保输出目录存在
  await Bun.write(join(generatedDir, '.keep'), '')

  // ===== 1. 扫描 models/**/schema.ts =====
  const schemaGlob = new Glob('**/schema.ts')
  const schemas: { folder: string; tableName: string; className: string }[] = []

  for await (const file of schemaGlob.scan({ cwd: modelsDir })) {
    const normalFile = file.replace(/\\/g, '/')
    // folder = 去掉尾部 /schema.ts 的相对路径，如 "topology/project" 或 "users"
    const folder = normalFile.replace(/\/schema\.ts$/, '')
    const content = await Bun.file(join(modelsDir, file)).text()
    const tableName = extractTableName(content)
    if (!tableName) {
      console.warn(`⚠️ Skipping ${file}: cannot find tableName export`)
      continue
    }
    // className 基于 tableName 生成（下划线分隔 → PascalCase + Schema）
    const className =
      tableName
        .split('_')
        .map((w) => w[0]!.toUpperCase() + w.slice(1))
        .join('') + 'Schema'
    schemas.push({ folder, tableName, className })
  }
  schemas.sort((a, b) => a.tableName.localeCompare(b.tableName))

  // ===== 2. 扫描 models/**/seed.ts =====
  const seedGlob = new Glob('**/seed.ts')
  const seeds: { folder: string; varName: string }[] = []

  for await (const file of seedGlob.scan({ cwd: modelsDir })) {
    const normalFile = file.replace(/\\/g, '/')
    const folder = normalFile.replace(/\/seed\.ts$/, '')
    // varName: 将路径分段用 _ 连接并 camelCase，如 topology/project → seed_topology_project
    const varName =
      'seed_' +
      folder
        .split('/')
        .map((seg) => kebabToCamel(seg))
        .join('_')
    seeds.push({ folder, varName })
  }
  seeds.sort((a, b) => a.folder.localeCompare(b.folder))

  // ===== 3. 扫描 api/**/*.ts =====
  const apiGlob = new Glob('**/*.ts')
  const apiFiles: { file: string; prefix: string; varName: string }[] = []

  for await (const file of apiGlob.scan({ cwd: apiDir })) {
    const normalFile = file.replace(/\\/g, '/')
    // 跳过配置文件（不是路由）
    if (normalFile.endsWith('/config.ts') || normalFile === 'config.ts') continue
    if (normalFile.endsWith('/policy.ts') || normalFile === 'policy.ts') continue

    apiFiles.push({
      file: normalFile,
      prefix: fileToPrefix(normalFile),
      varName: pathToVar(normalFile, 'route'),
    })
  }
  apiFiles.sort((a, b) => a.file.localeCompare(b.file))

  // ===== 4. 扫描 services 中导出 init 函数的文件 =====
  // 扫描 services/*.ts（扁平文件）和 services/*/index.ts（文件夹入口）
  const servicesDir = join(dir, 'services')
  const services: { file: string; varName: string; name: string }[] = []

  const servicePaths = [
    ...Array.from(new Glob('*.ts').scanSync({ cwd: servicesDir })),
    ...Array.from(new Glob('*/index.ts').scanSync({ cwd: servicesDir })),
  ]

  for (const file of servicePaths) {
    const normalFile = file.replace(/\\/g, '/')
    const content = await Bun.file(join(servicesDir, normalFile)).text()
    // 匹配 export async function init 或 export function init
    if (!/export\s+(async\s+)?function\s+init\s*\(/.test(content)) continue
    // services/rate-limit.ts → "rate-limit", services/rbac/index.ts → "rbac"
    const name = normalFile.replace(/\/index\.ts$/, '').replace(/\.ts$/, '')
    services.push({
      file: normalFile,
      name,
      varName: 'svc_' + kebabToCamel(name),
    })
  }
  services.sort((a, b) => a.name.localeCompare(b.name))

  // ===== 生成 _generated/model.generated.ts（类型定义） =====
  {
    const lines = header()
    lines.push("import type { Model, SchemaDefinition, InstanceKeys } from '@pkg/orm'")
    lines.push('')
    for (const { folder, className } of schemas) {
      lines.push(`import type ${className} from '@/models/${folder}/schema'`)
    }
    lines.push('')
    lines.push('/** 从 Schema 类推导 Model 类型 */')
    lines.push(
      'type ModelOf<C extends abstract new (...args: any) => any> = Model<SchemaDefinition, InstanceKeys<C>>',
    )
    lines.push('')
    lines.push('/** 模型注册表类型（自动生成） */')
    lines.push('export interface ModelRegistry {')
    for (const { tableName, className } of schemas) {
      lines.push(`  ${tableName}: ModelOf<typeof ${className}>`)
    }
    lines.push('}')
    lines.push('')
    if (schemas.some((e) => e.tableName === 'session')) {
      lines.push('/** Session 相关类型 */')
      lines.push("export type SessionRow = import('@pkg/orm').Row<ModelRegistry['session']>")
      lines.push("export type SessionInsert = import('@pkg/orm').Insert<ModelRegistry['session']>")
      lines.push("export type SessionUpdate = import('@pkg/orm').Update<ModelRegistry['session']>")
      lines.push('')
    }
    await Bun.write(join(generatedDir, 'model.generated.ts'), lines.join('\n'))
    console.log(
      `✅ Generated model types → _generated/model.generated.ts (${schemas.length} models)`,
    )
  }

  // ===== 生成 _generated/schemas.generated.ts（运行时 Schema 导入） =====
  {
    const lines = header()
    for (const { folder, className } of schemas) {
      const varTable =
        folder
          .split('/')
          .map((seg) => kebabToCamel(seg))
          .join('_') + '_tableName'
      lines.push(
        `import ${className}, { tableName as ${varTable} } from '@/models/${folder}/schema'`,
      )
    }
    lines.push('')
    lines.push('// Schema 模块注册表 — 自动生成自 models/**/schema.ts')
    lines.push('export const schemaModules = [')
    for (const { className, folder } of schemas) {
      const varTable =
        folder
          .split('/')
          .map((seg) => kebabToCamel(seg))
          .join('_') + '_tableName'
      lines.push(`  { tableName: ${varTable}, Schema: ${className} },`)
    }
    lines.push(']')
    lines.push('')
    await Bun.write(join(generatedDir, 'schemas.generated.ts'), lines.join('\n'))
    console.log(
      `✅ Generated schema registry → _generated/schemas.generated.ts (${schemas.length} schemas)`,
    )
  }

  // ===== 生成 _generated/routes.generated.ts（运行时 API 路由导入） =====
  {
    const lines = header()
    for (const { file, varName } of apiFiles) {
      const importPath = file.replace(/\.ts$/, '')
      lines.push(`import ${varName} from '@/api/${importPath}'`)
    }
    lines.push('')
    lines.push('// API 路由注册表 — 自动生成自 api{/}**/*.ts')
    lines.push('export const apiRoutes = [')
    for (const { prefix, varName } of apiFiles) {
      lines.push(`  { prefix: '${prefix}', module: ${varName} },`)
    }
    lines.push(']')
    lines.push('')
    await Bun.write(join(generatedDir, 'routes.generated.ts'), lines.join('\n'))
    console.log(
      `✅ Generated API routes → _generated/routes.generated.ts (${apiFiles.length} routes)`,
    )
  }

  // ===== 生成 _generated/seeds.generated.ts（运行时 Seed 导入） =====
  {
    const lines = header()
    for (const { folder, varName } of seeds) {
      lines.push(`import * as ${varName} from '@/models/${folder}/seed'`)
    }
    lines.push('')
    lines.push('// Seed 模块注册表 — 自动生成自 models/**/seed.ts')
    lines.push('export const seedModules: Record<string, unknown>[] = [')
    for (const { varName } of seeds) {
      lines.push(`  ${varName},`)
    }
    lines.push(']')
    lines.push('')
    await Bun.write(join(generatedDir, 'seeds.generated.ts'), lines.join('\n'))
    console.log(
      `✅ Generated seed registry → _generated/seeds.generated.ts (${seeds.length} seeds)`,
    )
  }

  // ===== 生成 _generated/configs.generated.ts（模块配置导入注册表） =====
  {
    const configGlob = new Glob('**/config.ts')
    const moduleConfigs: { file: string; varName: string; dir: string }[] = []
    const groupConfigs: { file: string; varName: string; dir: string }[] = []

    for await (const file of configGlob.scan({ cwd: apiDir })) {
      const normalFile = file.replace(/\\/g, '/')
      const varName =
        'config_' +
        normalFile
          .replace(/\/config\.ts$/, '')
          .split('/')
          .map((seg) => (seg === '_' ? '$' : kebabToCamel(seg)))
          .join('_')
      // 生成与路由 prefix 匹配的 dir key（去掉 _ 段）
      const dir = normalFile
        .replace(/\/config\.ts$/, '')
        .split('/')
        .filter((seg) => seg !== '_')
        .join('/')

      // 读取文件内容判断是 GroupConfig 还是 ModuleConfig
      const content = await Bun.file(join(apiDir, file)).text()
      const isGroup = content.includes('defineGroupConfig')

      if (isGroup) {
        groupConfigs.push({ file: normalFile, varName, dir })
      } else {
        moduleConfigs.push({ file: normalFile, varName, dir })
      }
    }
    moduleConfigs.sort((a, b) => a.file.localeCompare(b.file))
    groupConfigs.sort((a, b) => a.file.localeCompare(b.file))
    const allConfigFiles = [...moduleConfigs, ...groupConfigs].sort((a, b) =>
      a.file.localeCompare(b.file),
    )

    const lines = header()
    lines.push("import type { ModuleConfig, GroupConfig } from '@/core/policy'")
    lines.push('')
    for (const { file, varName } of allConfigFiles) {
      const importPath = file.replace(/\.ts$/, '')
      lines.push(`import ${varName} from '@/api/${importPath}'`)
    }
    lines.push('')
    lines.push('// 模块配置注册表 — 自动生成自 api{/}**/config.ts（不含分组配置）')
    lines.push('export const allConfigs: ModuleConfig[] = [')
    for (const { varName } of moduleConfigs) {
      lines.push(`  ${varName},`)
    }
    lines.push(']')
    lines.push('')
    lines.push('// 分组配置注册表 — 自动生成自 api{/}**/config.ts（仅分组配置）')
    lines.push('export const allGroupConfigs: GroupConfig[] = [')
    for (const { varName } of groupConfigs) {
      lines.push(`  ${varName},`)
    }
    lines.push(']')
    lines.push('')
    lines.push('// 配置目录映射（含分组配置）— 用于 OpenAPI Tag 生成')
    lines.push('export const configByDir: Record<string, ModuleConfig | GroupConfig> = {')
    for (const { varName, dir } of allConfigFiles) {
      lines.push(`  '${dir}': ${varName},`)
    }
    lines.push('}')
    lines.push('')
    await Bun.write(join(generatedDir, 'configs.generated.ts'), lines.join('\n'))
    console.log(
      `✅ Generated config registry → _generated/configs.generated.ts (${moduleConfigs.length} modules, ${groupConfigs.length} groups)`,
    )
  }

  // ===== 生成 _generated/services.generated.ts（Service init 注册表） =====
  {
    const lines = header()
    for (const { name, varName } of services) {
      lines.push(`import { init as ${varName} } from '@/services/${name}'`)
    }
    lines.push('')
    lines.push('// Service 初始化注册表 — 自动生成自 services{/}*.ts（导出 init 函数的文件）')
    lines.push(
      'export const serviceInits: { name: string; init: () => Promise<void> | void }[] = [',
    )
    for (const { name, varName } of services) {
      lines.push(`  { name: '${name}', init: ${varName} },`)
    }
    lines.push(']')
    lines.push('')
    await Bun.write(join(generatedDir, 'services.generated.ts'), lines.join('\n'))
    console.log(
      `✅ Generated service inits → _generated/services.generated.ts (${services.length} services)`,
    )
  }
}

// ─── CLI 直接执行 ───
if (import.meta.main) {
  await generateRegistry()
}
