/**
 * Registry 生成脚本 & 编译时插件
 *
 * 扫描 models下的schema.ts / seed.ts 以及 api下的所有ts文件
 * 自动生成静态 import 注册表文件，替代运行时 Glob
 *
 * 生成产物：
 *   _generated/model.generated.ts     — Model 类型定义（type-only）
 *   _generated/schemas.generated.ts   — Schema 运行时导入注册表
 *   _generated/routes.generated.ts    — API 路由运行时导入注册表
 *   _generated/seeds.generated.ts     — Seed 运行时导入注册表
 *   _generated/configs.generated.ts   — 模块配置运行时导入注册表
 *
 * 使用方式：
 *   bun run scripts/gen-registry.ts        # 直接执行
 *   import { generateRegistry } from '...' # 在 build.ts 中作为编译时插件调用
 */

import { Glob } from 'bun'
import { join, resolve } from 'path'

// ─── 工具函数 ───

/** kebab-case → camelCase */
function kebabToCamel(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
}

/** kebab-case → PascalCase */
function kebabToPascal(s: string): string {
  return s
    .split('-')
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join('')
}

/**
 * 文件路径 → API prefix（与原 core/index.ts fileToPrefix 逻辑一致）
 *   admin/auth/index.ts  → api/admin/auth
 *   _/auth/index.ts      → api/auth
 */
function fileToPrefix(file: string): string {
  const parts = file
    .replace(/\\/g, '/')
    .replace(/\.ts$/, '')
    .split('/')
    .filter((seg) => seg !== '_')
  if (parts.at(-1) === 'index') parts.pop()
  return `api/${parts.join('/')}`
}

/** 文件路径 → 合法 JS 变量名 */
function pathToVar(file: string, prefix: string): string {
  return (
    prefix +
    '_' +
    file
      .replace(/\\/g, '/')
      .replace(/\.ts$/, '')
      .replace(/\/index$/, '')
      .split('/')
      .map((seg) => (seg === '_' ? '$' : kebabToCamel(seg)))
      .join('_')
  )
}

/** 从 schema.ts 文件内容中提取 tableName（纯文本解析，不需要 import 模块） */
function extractTableName(content: string): string | null {
  const match = content.match(/export\s+const\s+tableName\s*=\s*['"]([^'"]+)['"]/)
  return match?.[1] ?? null
}

function header(): string[] {
  return [
    '// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY',
    '// Generated by: bun run scripts/gen-registry.ts',
    `// Generated at: ${new Date().toISOString()}`,
    '',
  ]
}

// ─── 核心生成逻辑 ───

/**
 * 生成所有注册表文件
 * @param backendDir - backend 目录的绝对路径（可选，默认自动推导）
 */
export async function generateRegistry(backendDir?: string) {
  const dir = backendDir ?? resolve(import.meta.dir, '..')
  const modelsDir = join(dir, 'models')
  const apiDir = join(dir, 'api')
  const generatedDir = join(dir, '_generated')

  // 确保输出目录存在
  await Bun.write(join(generatedDir, '.keep'), '')

  // ===== 1. 扫描 models/*/schema.ts =====
  const schemaGlob = new Glob('*/schema.ts')
  const schemas: { folder: string; tableName: string; className: string }[] = []

  for await (const file of schemaGlob.scan({ cwd: modelsDir })) {
    const folder = file.replace(/\\/g, '/').split('/')[0]!
    const content = await Bun.file(join(modelsDir, file)).text()
    const tableName = extractTableName(content)
    if (!tableName) {
      console.warn(`⚠️ Skipping ${file}: cannot find tableName export`)
      continue
    }
    schemas.push({ folder, tableName, className: kebabToPascal(folder) + 'Schema' })
  }
  schemas.sort((a, b) => a.tableName.localeCompare(b.tableName))

  // ===== 2. 扫描 models/*/seed.ts =====
  const seedGlob = new Glob('*/seed.ts')
  const seeds: { folder: string; varName: string }[] = []

  for await (const file of seedGlob.scan({ cwd: modelsDir })) {
    const folder = file.replace(/\\/g, '/').split('/')[0]!

    seeds.push({ folder, varName: 'seed_' + kebabToCamel(folder) })
  }
  seeds.sort((a, b) => a.folder.localeCompare(b.folder))

  // ===== 3. 扫描 api/**/*.ts =====
  const apiGlob = new Glob('**/*.ts')
  const apiFiles: { file: string; prefix: string; varName: string }[] = []

  for await (const file of apiGlob.scan({ cwd: apiDir })) {
    const normalFile = file.replace(/\\/g, '/')
    // 跳过配置文件（不是路由）
    if (normalFile.endsWith('/config.ts') || normalFile === 'config.ts') continue
    if (normalFile.endsWith('/policy.ts') || normalFile === 'policy.ts') continue

    apiFiles.push({
      file: normalFile,
      prefix: fileToPrefix(normalFile),
      varName: pathToVar(normalFile, 'route'),
    })
  }
  apiFiles.sort((a, b) => a.file.localeCompare(b.file))

  // ===== 生成 _generated/model.generated.ts（类型定义） =====
  {
    const lines = header()
    lines.push("import type { Model, SchemaDefinition, InstanceKeys } from '@pkg/orm'")
    lines.push('')
    for (const { folder, className } of schemas) {
      lines.push(`import type ${className} from '@/models/${folder}/schema'`)
    }
    lines.push('')
    lines.push('/** 从 Schema 类推导 Model 类型 */')
    lines.push(
      'type ModelOf<C extends abstract new (...args: any) => any> = Model<SchemaDefinition, InstanceKeys<C>>',
    )
    lines.push('')
    lines.push('/** 模型注册表类型（自动生成） */')
    lines.push('export interface ModelRegistry {')
    for (const { tableName, className } of schemas) {
      lines.push(`  ${tableName}: ModelOf<typeof ${className}>`)
    }
    lines.push('}')
    lines.push('')
    if (schemas.some((e) => e.tableName === 'session')) {
      lines.push('/** Session 相关类型 */')
      lines.push("export type SessionRow = import('@pkg/orm').Row<ModelRegistry['session']>")
      lines.push("export type SessionInsert = import('@pkg/orm').Insert<ModelRegistry['session']>")
      lines.push("export type SessionUpdate = import('@pkg/orm').Update<ModelRegistry['session']>")
      lines.push('')
    }
    await Bun.write(join(generatedDir, 'model.generated.ts'), lines.join('\n'))
    console.log(`✅ Generated model types → _generated/model.generated.ts (${schemas.length} models)`)
  }

  // ===== 生成 _generated/schemas.generated.ts（运行时 Schema 导入） =====
  {
    const lines = header()
    for (const { folder, className } of schemas) {
      const varTable = kebabToCamel(folder) + '_tableName'
      lines.push(
        `import ${className}, { tableName as ${varTable} } from '@/models/${folder}/schema'`,
      )
    }
    lines.push('')
    lines.push('// Schema 模块注册表 — 自动生成自 models{/}*/schema.ts')
    lines.push('export const schemaModules = [')
    for (const { className, folder } of schemas) {
      const varTable = kebabToCamel(folder) + '_tableName'
      lines.push(`  { tableName: ${varTable}, Schema: ${className} },`)
    }
    lines.push(']')
    lines.push('')
    await Bun.write(join(generatedDir, 'schemas.generated.ts'), lines.join('\n'))
    console.log(
      `✅ Generated schema registry → _generated/schemas.generated.ts (${schemas.length} schemas)`,
    )
  }

  // ===== 生成 _generated/routes.generated.ts（运行时 API 路由导入） =====
  {
    const lines = header()
    for (const { file, varName } of apiFiles) {
      const importPath = file.replace(/\.ts$/, '')
      lines.push(`import ${varName} from '@/api/${importPath}'`)
    }
    lines.push('')
    lines.push('// API 路由注册表 — 自动生成自 api{/}**/*.ts')
    lines.push('export const apiRoutes = [')
    for (const { prefix, varName } of apiFiles) {
      lines.push(`  { prefix: '${prefix}', module: ${varName} },`)
    }
    lines.push(']')
    lines.push('')
    await Bun.write(join(generatedDir, 'routes.generated.ts'), lines.join('\n'))
    console.log(
      `✅ Generated API routes → _generated/routes.generated.ts (${apiFiles.length} routes)`,
    )
  }

  // ===== 生成 _generated/seeds.generated.ts（运行时 Seed 导入） =====
  {
    const lines = header()
    for (const { folder, varName } of seeds) {
      lines.push(`import * as ${varName} from '@/models/${folder}/seed'`)
    }
    lines.push('')
    lines.push('// Seed 模块注册表 — 自动生成自 models{/}*/seed.ts')
    lines.push('export const seedModules: Record<string, unknown>[] = [')
    for (const { varName } of seeds) {
      lines.push(`  ${varName},`)
    }
    lines.push(']')
    lines.push('')
    await Bun.write(join(generatedDir, 'seeds.generated.ts'), lines.join('\n'))
    console.log(`✅ Generated seed registry → _generated/seeds.generated.ts (${seeds.length} seeds)`)
  }

  // ===== 生成 _generated/configs.generated.ts（模块配置导入注册表） =====
  {
    const configGlob = new Glob('**/config.ts')
    const configFiles: { file: string; varName: string }[] = []

    for await (const file of configGlob.scan({ cwd: apiDir })) {
      const normalFile = file.replace(/\\/g, '/')
      const varName =
        'config_' +
        normalFile
          .replace(/\/config\.ts$/, '')
          .split('/')
          .map((seg) => (seg === '_' ? '$' : kebabToCamel(seg)))
          .join('_')
      configFiles.push({ file: normalFile, varName })
    }
    configFiles.sort((a, b) => a.file.localeCompare(b.file))

    const lines = header()
    lines.push("import type { ModuleConfig } from '@/core/policy'")
    lines.push('')
    for (const { file, varName } of configFiles) {
      const importPath = file.replace(/\.ts$/, '')
      lines.push(`import ${varName} from '@/api/${importPath}'`)
    }
    lines.push('')
    lines.push('// 模块配置注册表 — 自动生成自 api{/}**/config.ts')
    lines.push('export const allConfigs: ModuleConfig[] = [')
    for (const { varName } of configFiles) {
      lines.push(`  ${varName},`)
    }
    lines.push(']')
    lines.push('')
    await Bun.write(join(generatedDir, 'configs.generated.ts'), lines.join('\n'))
    console.log(
      `✅ Generated config registry → _generated/configs.generated.ts (${configFiles.length} configs)`,
    )
  }
}

// ─── CLI 直接执行 ───
if (import.meta.main) {
  await generateRegistry()
}
