import type { SeedDefinition } from '@/modules/seed'
import Menu from './index'

/** 默认菜单数据 - ID 硬编码确保父子关系正确 */
const defaultMenus = [
  // ========== 0. 控制台 ==========
  {
    id: 1,
    parentId: null,
    name: '控制台',
    path: '/dashboard',
    component: 'Dashboard',
    icon: 'home',
    type: 2, // 页面（单独页面，不是目录）
    visible: 1,
    status: 1,
    redirect: null,
    sort: 0,
    permCode: null, // 控制台不需要特殊权限，登录即可访问
  },

  // ========== 1. 系统管理目录 ==========
  {
    id: 2,
    parentId: null,
    name: '系统管理',
    path: '/system',
    component: null,
    icon: 'setting',
    type: 1, // 目录
    visible: 1,
    status: 1,
    redirect: '/system/users',
    sort: 1,
    permCode: null,
  },
  // 用户管理页面
  {
    id: 3,
    parentId: 2,
    name: '用户管理',
    path: '/system/users',
    component: 'admin/system/Users',
    icon: 'user',
    type: 2, // 页面
    visible: 1,
    status: 1,
    redirect: null,
    sort: 1,
    permCode: 'user:admin:list',
  },
  // 角色管理页面
  {
    id: 4,
    parentId: 2,
    name: '角色管理',
    path: '/system/roles',
    component: 'admin/system/Roles',
    icon: 'peoples',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 2,
    permCode: 'role:admin:list',
  },
  // 权限管理页面
  {
    id: 5,
    parentId: 2,
    name: '权限管理',
    path: '/system/permissions',
    component: 'admin/system/Permissions',
    icon: 'lock',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 3,
    permCode: 'permission:admin:list',
  },
  // 数据权限页面
  {
    id: 6,
    parentId: 2,
    name: '数据权限',
    path: '/system/permission-scopes',
    component: 'admin/system/PermissionScopes',
    icon: 'database',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 4,
    permCode: 'permission-scope:admin:list',
  },
  // 菜单管理页面
  {
    id: 7,
    parentId: 2,
    name: '菜单管理',
    path: '/system/menus',
    component: 'admin/system/Menus',
    icon: 'menu',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 5,
    permCode: 'menu:admin:list',
  },
  // 字典类型页面
  {
    id: 8,
    parentId: 2,
    name: '字典类型',
    path: '/system/dict-types',
    component: 'admin/system/DictTypes',
    icon: 'dict',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 6,
    permCode: 'dict:admin:type:list',
  },
  // 字典数据页面
  {
    id: 9,
    parentId: 2,
    name: '字典数据',
    path: '/system/dict-data',
    component: 'admin/system/DictData',
    icon: 'dict',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 7,
    permCode: 'dict:admin:data:list',
  },
  // 参数配置页面
  {
    id: 10,
    parentId: 2,
    name: '参数配置',
    path: '/system/configs',
    component: 'admin/system/Configs',
    icon: 'config',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 8,
    permCode: 'config:admin:list',
  },

  // ========== 2. 权限配置目录 ==========
  {
    id: 12,
    parentId: null,
    name: '权限配置',
    path: '/rbac',
    component: null,
    icon: 'security',
    type: 1,
    visible: 1,
    status: 1,
    redirect: '/rbac/role-menus',
    sort: 2,
    permCode: null,
  },
  // 角色菜单页面
  {
    id: 13,
    parentId: 12,
    name: '角色菜单',
    path: '/rbac/role-menus',
    component: 'admin/rbac/RoleMenus',
    icon: 'tree',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 1,
    permCode: 'role-menu:admin:list',
  },
  // 角色权限页面
  {
    id: 14,
    parentId: 12,
    name: '角色权限',
    path: '/rbac/role-permissions',
    component: 'admin/rbac/RolePermissions',
    icon: 'permission',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 2,
    permCode: 'role-permission:admin:list',
  },
  // 会话管理页面
  {
    id: 15,
    parentId: 12,
    name: '会话管理',
    path: '/rbac/sessions',
    component: 'admin/rbac/Sessions',
    icon: 'session',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 3,
    permCode: 'auth:admin:sessions',
  },
  // 缓存管理页面
  {
    id: 16,
    parentId: 12,
    name: '缓存管理',
    path: '/rbac/cache',
    component: 'admin/rbac/Cache',
    icon: 'cache',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 4,
    permCode: 'rbac:admin:cache-status',
  },

  // ========== 3. VIP管理目录 ==========
  {
    id: 17,
    parentId: null,
    name: 'VIP管理',
    path: '/vip',
    component: null,
    icon: 'vip',
    type: 1,
    visible: 1,
    status: 1,
    redirect: '/vip/tiers',
    sort: 3,
    permCode: null,
  },
  // VIP等级页面
  {
    id: 18,
    parentId: 17,
    name: 'VIP等级',
    path: '/vip/tiers',
    component: 'admin/vip/Tiers',
    icon: 'tier',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 1,
    permCode: 'vip:admin:tier:list',
  },
  // 用户VIP页面
  {
    id: 19,
    parentId: 17,
    name: '用户VIP',
    path: '/vip/users',
    component: 'admin/vip/Users',
    icon: 'vip-user',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 2,
    permCode: 'vip:admin:user:list',
  },
  // 资源限制页面
  {
    id: 20,
    parentId: 17,
    name: '资源限制',
    path: '/vip/resource-limits',
    component: 'admin/vip/ResourceLimits',
    icon: 'resource',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 3,
    permCode: 'vip:admin:resource-limit:list',
  },

  // ========== 4. 通知公告目录 ==========
  {
    id: 21,
    parentId: null,
    name: '通知公告',
    path: '/notice',
    component: null,
    icon: 'notice',
    type: 1,
    visible: 1,
    status: 1,
    redirect: '/notice/list',
    sort: 4,
    permCode: null,
  },
  // 公告管理页面
  {
    id: 22,
    parentId: 21,
    name: '公告管理',
    path: '/notice/list',
    component: 'admin/notice/Notices',
    icon: 'message',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 1,
    permCode: 'notice:admin:list',
  },

  // ========== 5. 文件管理目录 ==========
  {
    id: 23,
    parentId: null,
    name: '文件管理',
    path: '/file',
    component: null,
    icon: 'file',
    type: 1,
    visible: 1,
    status: 1,
    redirect: '/file/list',
    sort: 5,
    permCode: null,
  },
  // 文件列表页面
  {
    id: 24,
    parentId: 23,
    name: '文件列表',
    path: '/file/list',
    component: 'admin/file/Files',
    icon: 'folder',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 1,
    permCode: 'file:admin:list',
  },

  // ========== 6. 日志管理目录 ==========
  {
    id: 25,
    parentId: null,
    name: '日志管理',
    path: '/log',
    component: null,
    icon: 'log',
    type: 1,
    visible: 1,
    status: 1,
    redirect: '/log/oper',
    sort: 6,
    permCode: null,
  },
  // 操作日志页面
  {
    id: 26,
    parentId: 25,
    name: '操作日志',
    path: '/log/oper',
    component: 'admin/system/OperLogs',
    icon: 'edit',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 1,
    permCode: 'operLog:admin:list',
  },
  // 登录日志页面（从系统管理迁移到日志管理）
  {
    id: 27,
    parentId: 25,
    name: '登录日志',
    path: '/log/login',
    component: 'admin/system/LoginLogs',
    icon: 'login',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 2,
    permCode: 'loginLog:admin:list',
  },
  // 任务日志页面
  {
    id: 28,
    parentId: 25,
    name: '任务日志',
    path: '/log/job',
    component: 'admin/job/JobLogs',
    icon: 'log',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 3,
    permCode: 'job:admin:log:list',
  },

  // ========== 7. 定时任务目录 ==========
  {
    id: 29,
    parentId: null,
    name: '定时任务',
    path: '/job',
    component: null,
    icon: 'job',
    type: 1,
    visible: 1,
    status: 1,
    redirect: '/job/list',
    sort: 7,
    permCode: null,
  },
  // 任务管理页面
  {
    id: 30,
    parentId: 29,
    name: '任务管理',
    path: '/job/list',
    component: 'admin/job/Jobs',
    icon: 'list',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 1,
    permCode: 'job:admin:list',
  },

  // ========== 8. 限流保护目录 ==========
  {
    id: 31,
    parentId: null,
    name: '限流保护',
    path: '/rate-limit',
    component: null,
    icon: 'shield',
    type: 1,
    visible: 1,
    status: 1,
    redirect: '/rate-limit/rules',
    sort: 8,
    permCode: null,
  },
  // 限流规则页面
  {
    id: 32,
    parentId: 31,
    name: '限流规则',
    path: '/rate-limit/rules',
    component: 'admin/rate-limit/RateLimitRules',
    icon: 'setting',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 1,
    permCode: 'rateLimit:admin:rule:list',
  },
  // IP黑名单页面
  {
    id: 33,
    parentId: 31,
    name: 'IP黑名单',
    path: '/rate-limit/blacklist',
    component: 'admin/rate-limit/IpBlacklist',
    icon: 'lock',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 2,
    permCode: 'rateLimit:admin:blacklist:list',
  },

  // ========== 9. CRUD 管理目录 ==========
  {
    id: 34,
    parentId: null,
    name: 'CRUD管理',
    path: '/crud',
    component: null,
    icon: 'table',
    type: 1, // 目录
    visible: 1,
    status: 1,
    redirect: '/crud/tables',
    sort: 9,
    permCode: null,
  },
  // CRUD 表配置页面
  {
    id: 35,
    parentId: 34,
    name: '表配置',
    path: '/crud/tables',
    component: 'admin/crud/CrudTables',
    icon: 'setting',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 1,
    permCode: 'crud:admin:list',
  },
  // CRUD 数据测试页面
  {
    id: 36,
    parentId: 34,
    name: '数据测试',
    path: '/crud/test',
    component: 'admin/crud/CrudTest',
    icon: 'edit',
    type: 2,
    visible: 1,
    status: 1,
    redirect: null,
    sort: 2,
    permCode: 'crud:admin:list',
  },
]

/** 菜单表 Seed */
export const menuSeed: SeedDefinition = {
  name: 'menu-default',
  description: '初始化默认菜单数据',
  async run() {
    for (const menu of defaultMenus) {
      await Menu.create(menu)
    }
    console.log(`✅ 已创建 ${defaultMenus.length} 个默认菜单`)
  },
}

export default menuSeed
